export const ADD_USER_PROFILE = `user/ADD_USER_PROFILE`;
export const CHANGE_AUTHORIZATION_FLAG = `user/CHANGE_AUTHORIZATION_FLAG`;
export const CHANGE_EMAIL_VALIDATION_ERROR = `user/CHANGE_EMAIL_VALIDATION_ERROR`;
