root: true

env:
  es2020: true
  browser: true
  jest: true

parser: babel-eslint

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
 - react

extends:
 - htmlacademy/es6
 - plugin:react/recommended

settings:
  react:
    version: '16'

rules:
  comma-dangle:
    - error
    - always-multiline
